spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql:///openapi
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true